### ISSUE TITLE
피드백

### ISSUE THREAD

**Issue by zzangoobrother** [ingwon97/Post_API#1]
1. @RequestMapping 보다는 @PostMapping, @GetMapping을 사용하세요.
2. CustomExceptionHandler 가 controller 패키지에 있는데 controll 보다는 다른 패키지에 있는게 좋습니다.
3. 연관관계에서 양방향을 주로 사용하셨는데 단방향을 하시고, 꼭 양방향이 필요하면 사용하셔야 합니다.
4. validate 메소드에서 ! 를 사용하였는데 팀 프로젝트에서는 안 좋습니다. 대부분의 사람들은 같은 객체 일때 참이 나올거라 생각하기 때문입니다.
5.  UserDetailsImpl 클래스는 security의  UserDetails를 상속받습니다. 과연 domain 패키지에 있는게 맞을까요?
6. System.out.println() 는 사용하시면 안됩니다. log 를 사용하세요

**Comment by Inkwon97** [comment]
감사합니다!
 
-----Original Message-----
From: "Choi Seon ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2022-08-13 (토) 14:17:53 (GMT+09:00)
Subject: [ingwon97/Post_API] 피드백 (Issue #1)
 

@RequestMapping 보다는 @PostMapping, @GetMapping을 사용하세요.
CustomExceptionHandler 가 controller 패키지에 있는데 controll 보다는 다른 패키지에 있는게 좋습니다.
연관관계에서 양방향을 주로 사용하셨는데 단방향을 하시고, 꼭 양방향이 필요하면 사용하셔야 합니다.
validate 메소드에서 ! 를 사용하였는데 팀 프로젝트에서는 안 좋습니다. 대부분의 사람들은 같은 객체 일때 참이 나올거라 생각하기 때문입니다.
UserDetailsImpl 클래스는 security의 UserDetails를 상속받습니다. 과연 domain 패키지에 있는게 맞을까요?
System.out.println() 는 사용하시면 안됩니다. log 를 사용하세요
